name: C/C++ CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: check cpputest dependency version
      run: echo "CPPUTEST_VERSION=$(git submodule status | awk '{print $1}')" >> $GITHUB_ENV
    - name: cache
      id: cache
      uses: actions/cache@v2
      with:
        path: cpputest
        key: ${{ runner.os }}-cpputest-${{ env.CPPUTEST_VERSION }}
    - name: init
      run: ./init
      if: steps.cache.outputs.cache-hit != 'true'
    - name: make
      run: make
      working-directory: source
