name: C/C++ CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: check cpputest dependency version
      run: echo "CPPUTEST_VERSION=$(git submodule status | awk '{print $1}')" >> $GITHUB_ENV
    - name: cache
      id: cache
      uses: actions/cache@v2
      with:
        path: cpputest
        key: ${{ runner.os }}-cpputest-${{ env.CPPUTEST_VERSION }}
    - name: make
      run: make
    - name: install doxygen
      run: sudo apt install -y doxygen graphviz
    - name: generate documentation
      run: doxygen
    - name: upload documentation
      uses: actions/upload-artifact@v2
      with:
        name: queue-doc
        path: doc/html
